compileRunDelete:
	gcc -Wall -o main suma.c

	g++ -Wall -o mainpp suma.cpp

	echo "programa en C"
	./main 2.1 2 2 

	echo "programa en C++"
	./mainpp 2.1 2 2 

	echo "programa en Python"
	python suma.py 2.1 2 2

	rm main mainpp
